config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  get '/locations', to: 'application#show'
  post '/ebird', to: 'ebird#data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
  validates :name, :icon, presence: true
  validates :name, uniqueness: true

  has_many :location_facilities
  has_many :locations, through: :location_facilities
end

app/models/location.rb
class Location < ApplicationRecord
	validates_presence_of :name
	validates_presence_of :description
	validates_presence_of :longitude
	validates_presence_of :latitude
	validates_presence_of :short_desc
	validates_presence_of :picURL

        has_many :location_facilities
        has_many :facilities, through: :location_facilities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include EbirdHelper
  def index
    calc_location()
    @locations_full = Location.all.sort_by{|location| hav_distance([location.latitude.to_f, location.longitude.to_f], @current_location)}
  end

  def show
    calc_location()
  	@locations_full = Location.all
  end

  def calc_location
    @current_location = [37.8039, -122.2591]
    if IPAddress.valid? request.remote_ip and request.remote_ip != '127.0.0.1'
      user_IP = request.remote_ip
      results = Geocoder.search(user_IP)
      if results.first.coordinates and results.first.coordinates.any?
        @current_location = results.first.coordinates
      end
    end
  end
end

app/controllers/ebird_controller.rb
require 'net/http'
require 'json'
include ActionView::Helpers::NumberHelper

class EbirdController < ApplicationController
  include EbirdHelper
  def data
      lat = params[:lat]
      lng = params[:lng]
      num_req = params[:num_req].to_i || 100
      num_ret = params[:num_ret].to_i || 1
      selected_birds = getBirdData(lat, lng, num_req, num_ret)
      img_src = []
      selected_birds.each { |bird_data|
          img_src.append(getImageSrc(bird_data))
      }
      render :json => {'imgsrc':img_src,'birddata':selected_birds}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ebird_helper.rb
require 'faraday'
require 'json'
include ActionView::Helpers::NumberHelper

module EbirdHelper
  def getBirdData(lat,lng, num_req=100, num_ret=1)
    ebird_params = {  :lat => number_with_precision(lat, precision: 2),
                      :lng => number_with_precision(lng, precision: 2),
                      :maxResults => num_req,
                      :back => 10,
                      :dist => 25,
                    }

    url = "https://api.ebird.org/v2/data/obs/geo/recent/"

    resp = Faraday.get(url) do |req|
      req.params = ebird_params
      req.headers = {"X-eBirdApiToken" => "a9qvaguuedjc"}
    end

    body = resp.body


    bird_data = select_random_birds(JSON.parse(body),num_ret)


    #bird_data = addBirdDist(lat, lng, bird_data)
    bird_data.each do |bird|
      bird["distTo"] = number_with_precision(hav_distance([lat.to_f,lng.to_f],
                                          [ bird["lat"].to_f,bird["lng"].to_f],
                                          true), precision: 1);
    end
    return bird_data

  end

  #need to make new function to stub it dumb hate this
  def select_random_birds(birds, num_ret)
    birds.sample(num_ret)
  end

  #def addBirdDist(lat,lng,bird_data)
  #    bird_data.map {|x| haversine_distance_wrapper(x,3)}
  #    haversine_distance(lat,lng,bird_data)
  #end

  def hav_distance(geo_a, geo_b, miles=false)
    # Get latitude and longitude
    lat1, lon1 = geo_a
    lat2, lon2 = geo_b

    # Calculate radial arcs for latitude and longitude
    dLat = (lat2 - lat1) * Math::PI / 180
    dLon = (lon2 - lon1) * Math::PI / 180


    a = Math.sin(dLat / 2) *
        Math.sin(dLat / 2) +
        Math.cos(lat1 * Math::PI / 180) *
        Math.cos(lat2 * Math::PI / 180) *
        Math.sin(dLon / 2) * Math.sin(dLon / 2)

     c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))

    d = 6371 * c * (miles ? 1 / 1.6 : 1)
  end

  def getImageSrc(bird_data)
    img_src = 'never set'
    begin
      img_src = getImageFromName(bird_data["comName"])
    rescue NoMethodError => e1
      begin
        img_src = getImageFromName(bird_data["sciName"])
      rescue NoMethodError => e2
        img_src = nil
      end
    end
    return img_src
  end



  def getImageFromName(name)

    wikimedia_params = {
      :action => "query",
      :prop => "pageimages",
      :format => "json",
      :piprop => "original",
      :titles => name,
      :redirects => 1
    }


    resp = Faraday.get("https://en.wikipedia.org/w/api.php") do |req|
      req.params = wikimedia_params
    end

    body = resp.body
    image_data = JSON.parse(body)

    image_pages = image_data["query"]["pages"]
    first_page = image_pages[image_pages.keys[0]]
    image_src = first_page["original"]["source"]

    return image_src

  end
end

app/views/application/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 navigation">
      <div id="logo">
        <center>
          <h2 style="padding-top:5px;">
            <%= image_tag "sfbbo-logo.jpg" %>
            <%= link_to 'BIRDING THE BAY TRAIL', root_path, {:style=>'color:#000000; text-decoration:none;', } %>
          </h2>
        </center>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="row">
        <h5>Nearby Locations</h5>
      </div>
      <div class="row">
        <%= link_to 'Show All Locations', locations_path%>
      </div>
      <div class="row">
        <div id="nearby-locations-sidenav" class="sidenav">
          <% @locations_full.each do |location| %>
            <div id="location-card" class="card">
              <div class="card-body">
                <h5> <%=link_to location.name, location.websiteURL %> </h5>
                <p class="card-text" style="font-size: 12px;"><h5><%= number_with_precision(hav_distance([location.latitude.to_f, location.longitude.to_f], @current_location), precision: 2) %> mi</h5></p>
              </div>
            </div>
            <br>
            <%= content_tag :div, class: "j-location_info", data: {loc: location} do %><% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
       <div id="mapid" style="height:500px"></div>
    </div>

    <div class="col-md-2">
      <div id="js-com_bird_info" class="card">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div id="RecentBirdSightings">
        <center>
          <h3>Recent Bird Sightings</h3>
        </center>
        <div id="RecentBirdList">
          <div id="header">
            <center>Click on a location pin to see recent bird sightings there in the past 30 days.</center>
          </div>
          <div class="scrolling-wrapper">
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
            <div class="card"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 navigation" style="padding: 0 !important;">
      <div id="logo">
        <div class="paragraph" style="text-align:center;">
          San Francisco Bay Bird Observatory <font size="1">●</font>&nbsp;
          <a href="https://maps.google.com/?q=524+Valley+Way,+Milpitas,+CA+95036&amp;entry=gmail&amp;source=g">
            524 Valley Way, Milpitas, CA 95035</a>&nbsp;<font size="1">●</font>
            408-946-6548&nbsp;<font size="1">●</font>
            <a href="mailto:outreach@sfbbo.org" target="_blank">outreach@sfbbo.org</a><br>
        </div>
        <center>Images from Wikipedia</center>
      </div>
    </div>
  </div>
</div>







<script>
  window.addEventListener("load", function() {
    var greenIcon = new L.Icon({
      iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-green.png',
      shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41]
    });
    var blueIcon = new L.Icon({
      iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png',
      shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41]
    });
    var yellowIcon = new L.Icon({
      iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-yellow.png',
      shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41]
    });

    var bird_data = null;
    var bird_images = null;
    var mymap = L.map('mapid').setView([37.42, -121.91], 13);
    L.tileLayer('https://{s}.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey={apikey}', {
        attribution: '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        apikey: 'df20324a5586441197c9410773b4ce60',
        maxZoom: 22
     }).addTo(mymap);

    var legend = L.control({position: 'topright'});
    legend.onAdd = function (map) {
      var div = L.DomUtil.create('div', 'legend');
      div.innerHTML +=  '<img src="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png" height=41 width=25>'  + 'Your Location' + '<br>'
      div.innerHTML +=  '<img src="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-gold.png" height=41 width=25>' + 'Bird-Watching Park' + '<br>'
      div.innerHTML +=  '<img src="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-blue.png" height=41 width=25>'   +  'Recent Bird Sighting'
      div.style.background = "silver"
      return div;
    };
    legend.addTo(mymap);

    function setContent(birddata,imgsrc,elem){
      $(elem).empty();
      $(elem).append(
        `
        <img class="card-img-top" src="${imgsrc}">
        <div class="card-body">
          <h5 class="card-title">${birddata.comName}</h5>
          <h6 class="card-subtitle mb-2 text-muted">${birddata.sciName}</h6>
          <p class="card-text">${birddata.distTo} miles away, at ${birddata.locName}</p>
          <p class="card-text">reported ${ moment(birddata.obsDt).fromNow()  }</p>
        </div>
        <a href="https://ebird.org/species/${birddata.speciesCode}" class="btn btn-primary">View On Ebird</a>
        `
      );
    }



    function setContentLoc(i, birddata,imgsrc,elem){
      $(elem)[i].innerHTML +=
        `
          <center>
          <img class="card-img-top" src="${imgsrc}" style="width: 10rem; height: 10rem;">
          </center>
          <div class="card-body" style="padding: 0">
            <a href="https://ebird.org/species/${birddata.speciesCode}"> <h5 class="card-title">${birddata.comName}</h5> </a>
            <h6 class="card-subtitle mb-2 text-muted">${birddata.sciName}</h6>
            <h6> <p>Last Seen: ${ moment(birddata.obsDt).fromNow()  }</p></h6>
          </div>
        `;
    }

    function setMarker(birddata, index){
      marker = new L.Marker(
        L.latLng(birddata.lat, birddata.lng),
        {name: `bird_marker_${index}`, icon: blueIcon}
      );
      mymap.addLayer(marker);
      marker.bindPopup(`<b>${birddata.comName}</b><br/>${birddata.sciName}.`).openPopup();
      marker.on('click', markerOnClick);
      return marker
    }

    function setLoc(loc_data){
      marker = new L.Marker(
        L.latLng(loc_data.latitude, loc_data.longitude),
        {name: loc_data.name, icon: yellowIcon}
      );
      mymap.addLayer(marker);
      URL_loc = loc_data.name.replace(/ /g, "+");
      marker.bindPopup(`<center><b>${loc_data.name}</b></center>
                        <br/><img src="${loc_data.picURL}" width=300 height=200>
                        <br/> ${loc_data.short_desc}
                        <br/><a href="${loc_data.websiteURL}">Website</a>
                        <br/> <a href="https://www.google.com/maps/dir/?api=1&destination=${URL_loc}">Get Directions</a>`).openPopup();
      marker.on('click', locMarkerOnClick);
      return marker
    }

    function getLocation(){
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(parallelHitEbirdEndpoint);
      } else {
        parallelHitEbirdEndpoint(null, new Error("no location"));
      }
    }

    function markerOnClick(e){
      i = this.options.name.slice(-1);
      setContent(bird_data[i],bird_images[i],$("#js-com_bird_info"));
    }

    function locMarkerOnClick(e){
      console.log("LOC MARKER CLICKED.");
      loc_name = e["sourceTarget"]["options"]["name"];
      lat = e.latlng["lat"];
      lng = e.latlng["lng"];
      var settings = {"url": "/ebird",
                      "method": "POST",
                      "timeout": 0,
                      "data":{
                          "authenticity_token" : "<%= form_authenticity_token %>",
                          "lat": lat,
                          "lng": lng,
                          "num_req":100,
                          "num_ret":9
                          }
                      };
      $.ajax(settings).done(function (response) {
        console.log(response);
        bird_data_loc= response.birddata;
        bird_images_loc = response.imgsrc;
        var arrayLength = bird_data_loc.length;
        $("#RecentBirdList #header").html(`<center>Birds To Look Out For At ${loc_name}:</center>`);
        $("#RecentBirdList .scrolling-wrapper").html(`<div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>
                                                      <div class="card"></div>`);
        for (var i = 0; i < arrayLength; i++) {
          setContentLoc(i, bird_data_loc[i],bird_images_loc[i],$("#RecentBirdList .scrolling-wrapper .card"));
        }
      });
    }

    function createPos(form){
      pos = {'coords':{'latitude':parseFloat(form.lat.value),'longitude':parseFloat(form.lng.value)}}
      parallelHitEbirdEndpoint(pos)
    }


    async function parallelHitEbirdEndpoint(pos, err){
      if(err) {
        console.error(err);
        pos = {
          coords: {
            latitude: 37.8039,
            longitude: -122.2591
          }
        };
      }
      cur_pos = new L.LatLng(pos.coords.latitude, pos.coords.longitude)
      mymap.panTo(cur_pos);
      marker = new L.Marker(cur_pos,{icon: greenIcon});
      mymap.addLayer(marker);
      marker.bindPopup(`<b>You are here</b>`).openPopup();
      hitEbirdEndpoint(pos, false);

    }
    function hitEbirdEndpoint(pos){
      var settings = {"url": "/ebird",
                      "method": "POST",
                      "timeout": 0,
                      "data":{
                          "authenticity_token" : "<%= form_authenticity_token %>",
                          "lat": pos.coords.latitude,
                          "lng": pos.coords.longitude,
                          "num_req":100,
                          "num_ret":10
                          }
                      }
      $.ajax(settings).done(function (response) {
        console.log("ebird response", response);
        markers = []
        bird_data = response.birddata;
        bird_images = response.imgsrc;
        var arrayLength = bird_data.length;
        for (var i = 0; i < arrayLength; i++) {
          setContent(bird_data[i],bird_images[i],$("#js-com_bird_info"));
          markers.push(setMarker(bird_data[i],i))
        }
        var group = new L.featureGroup(markers);
        mymap.fitBounds(group.getBounds().pad(0.2));
      });
    }

    getLocation();
    $( ".j-location_info" ).each(function() {
      setLoc($(this).data('loc'));
    });
  });
</script>

app/views/application/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 navigation" style="padding: 0 !important;">
      <div id="logo">
        <center>

          <h2 style="margin-bottom: 0;padding-top:3px;">
            <%= image_tag "sfbbo-logo.jpg" %>
            <%= link_to 'BIRDING THE BAY TRAIL', root_path, {:style=>'color:#000000; text-decoration:none;', } %>

          </h2>
          ALL LOCATIONS
        </center>
        <hr>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card-columns">
      <% @locations_full.each do |location| %>
        <div class="card">
          <img class="card-img-top" src="<%= location.picURL %>" />
          <div class="card-body">
            <h5 id="location-name"><%= location.name %></h5>
            <h5><%= number_with_precision(hav_distance([location.latitude.to_f, location.longitude.to_f], @current_location), precision: 2) %> mi</h5>
            <p class="card-text" style="font-size: 14px;"><%= location.description %></p>
          </div>
          <div class="card-footer">
            <a href="<%= location.websiteURL %>" class="card-link" target="_blank">Website</a>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 navigation" style="padding: 0 !important;">
      <div id="logo">
        <div class="paragraph" style="text-align:center;">
          San Francisco Bay Bird Observatory <font size="1">●</font>&nbsp;
          <a href="https://maps.google.com/?q=524+Valley+Way,+Milpitas,+CA+95036&amp;entry=gmail&amp;source=g">
            524 Valley Way, Milpitas, CA 95035</a>&nbsp;<font size="1">●</font>
            408-946-6548&nbsp;<font size="1">●</font>
            <a href="mailto:outreach@sfbbo.org" target="_blank">outreach@sfbbo.org</a><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baytrailbirding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,900;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha512-tDXPcamuZsWWd6OsKFyH6nAqh/MjZ/5Yk88T5o+aMfygqNFPan1pLyPFAndRzmOWHKT+jSDzWpJv8krj6x1LMA==" crossorigin="anonymous" />

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'main', media: 'all' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha512-Ah5hWYPzDsVHf9i2EejFBFrG2ZAPmpu4ZJtW4MfSgpZacn+M9QHDt+Hd/wL1tEkk1UgbzqepJr6KnhZjFKB+0A==" crossorigin="anonymous"></script>
  </body>
</html>